### ISSUE TITLE
在线收新消息会重复收到新消息。好像是没回调ack。

### ISSUE THREAD

**Issue by huioff** [WuKongIM/WuKongIMFlutterSDK#11]
![WechatIMG439](https://github.com/WuKongIM/WuKongIMFlutterSDK/assets/39048090/7e772821-57ec-4ba7-8e4d-ab2cbd2cb12c)
![WechatIMG440](https://github.com/WuKongIM/WuKongIMFlutterSDK/assets/39048090/fadfde71-95bf-4dff-ab21-6b96ea4b28b2)

**Comment by No8blackball** [comment]
回ack有bug，1.1.9版本已经修复了
