### ISSUE TITLE
后台挂一段时间后再次进入 会卡在连接中

### ISSUE THREAD

**Issue by a983132370** [WuKongIM/WuKongIMFlutterSDK#16]
<img width="1168" alt="d474bf6baa3a1f7fbc936203b377cc9" src="https://github.com/WuKongIM/WuKongIMFlutterSDK/assets/21359946/4b2d0cd3-4388-431c-86a2-847b24f46237">
<img width="394" alt="efa20f4f5f8d96e38c6f7079d44a06f" src="https://github.com/WuKongIM/WuKongIMFlutterSDK/assets/21359946/e85fcb61-deb3-4d8d-be06-b88f3dc85f34">

wukongimfluttersdk: ^1.2.3

ping信息也报错
StreamSink is bound to a stream

调用也就无法退出
WKIM.shared.connectionManager.disconnect(true);

**Comment by No8blackball** [comment]
更新到1.2.4
