### ISSUE TITLE
频道未读消息的bug

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIMFlutterSDK#19]
当前频道红点有值的时候，使用updateRedDot方法把红点标0后，然后在频道中再次发一条消息，下次重启app同步消息得时候，这个红点的值会恢复成之前的状态，比如我之前5条未读，我发了一条消息，我退出频道的时候清空了未读红点，然后我重启App 同步消息的时候 红点又变成了5。

**Comment by xiaowas** [comment]
请问你怎么解决的
