### ISSUE TITLE
发送消息附带WKReply会报错

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIMFlutterSDK#20]
发送消息附带WKReply会报错 json解析错误，我看了一下好像是转成json的格式不对 json里面字段字段和值都没有引号。

**Comment by No8blackball** [comment]
> 发送消息附带WKReply会报错 json解析错误，我看了一下好像是转成json的格式不对 json里面字段字段和值都没有引号。

更新至1.3.0版本
