### ISSUE TITLE
消息记录循环请求的问题

### ISSUE THREAD

**Issue by doralines** [WuKongIM/WuKongIMFlutterSDK#21]
sdk有一个循环请求的BUG 下图我在demo中打印的一个，基本上必现，就是在拉取消息记录同步的时候，每次都是请求五次，服务端日志打印我看也是五次请求  
下面是直接在demo中打印的 参数两个1 这个群聊或者其他可以翻页的群聊 都可以必现
![8815b5fc29abe32573bd10b344be30b](https://github.com/WuKongIM/WuKongIMFlutterSDK/assets/150234314/76c5f622-c4e3-469b-bb77-89207ff3aa27)
![2a1b6f0f454071f1f4b6f7ff71b9ea5](https://github.com/WuKongIM/WuKongIMFlutterSDK/assets/150234314/70d43751-d883-40b2-8081-1d9b4b3c9175)
![5c109925a89a4ea3ff480c5341d8087](https://github.com/WuKongIM/WuKongIMFlutterSDK/assets/150234314/2854cd8a-588b-429f-8939-5b808813ada8)

**Comment by No8blackball** [comment]
1.3.1版本已修复
