### ISSUE TITLE
把所有频道的未读消息清零，有什么方法吗？

### ISSUE THREAD

**Issue by wuweijian1997** [WuKongIM/WuKongIMFlutterSDK#23]
把所有频道的未读消息清零，有什么方法吗？

**Comment by No8blackball** [comment]
更新至1.3.6版本
可通过以下方法清空本地所有未读数量
`WKIM.shared.conversationManager.clearAllRedDot();`
同时UI可通过
`WKIM.shared.conversationManager
        .addOnClearAllRedDotListener("chat_conversation", () {
     // 刷新UI
    });`
方法监听红点清除
