### ISSUE TITLE
WKIM实例未初始化时调用WKIM.shared.connectionManager.disconnect(true)报空值异常

### ISSUE THREAD

**Issue by vera-byte** [WuKongIM/WuKongIMFlutterSDK#28]
<img width="1082" alt="image" src="https://github.com/WuKongIM/WuKongIMFlutterSDK/assets/42960387/f9ff3636-8381-4b53-85d2-88a853fdb4e0">

**Comment by No8blackball** [comment]
1.4.7已修复
