### ISSUE TITLE
flutter sdk错误

### ISSUE THREAD

**Issue by colbort** [WuKongIM/WuKongIMFlutterSDK#29]
<img width="1367" alt="image" src="https://github.com/WuKongIM/WuKongIMFlutterSDK/assets/47207881/11f578d6-4c3e-4779-afe1-2fa2598e0eca">

**Comment by No8blackball** [comment]
> <img width="1367" alt="image" src="https://github.com/WuKongIM/WuKongIMFlutterSDK/assets/47207881/11f578d6-4c3e-4779-afe1-2fa2598e0eca">
> 

更新1.3.8试下
