### ISSUE TITLE
消息解析错误

### ISSUE THREAD

**Issue by unicornB** [WuKongIM/WuKongIMFlutterSDK#3]
_TypeError (type 'Null' is not a subtype of type 'String')
E/flutter (21349): #0      WKMessageManager.parsingMsg              message_manager.dart:67
E/flutter (21349): #1      WKConnectionManager._saveRecvMsg      connect_manager.dart:402

**Comment by tangtaoit** [comment]
Upgrade to the latest

**Comment by unicornB** [comment]
已解决
