### ISSUE TITLE
FlutterSDK没有搜索本地数据库聊天记录和群聊的方法

### ISSUE THREAD

**Issue by hellozhanxiang** [WuKongIM/WuKongIMFlutterSDK#30]
如题，参考唐僧叨叨Android端的搜索功能，Android SDK有搜索本地聊天记录、群聊功能的方法，Flutter SDK里没有这个方法和相应实现，能否添加上？

![唐僧叨叨搜索功能](https://github.com/user-attachments/assets/3c150128-ba87-4e0b-8c69-3ae9d9ba17ce)

**Comment by No8blackball** [comment]
频道相关搜索：
` WKIM.shared.channelManager.search(‘全局搜索');`
`WKIM.shared.channelManager.searchWithChannelTypeAndFollow('搜索好友',WKChannelType.personal,1);`
消息相关搜索
` WKIM.shared.messageManager.search('全局搜索');`
`WKIM.shared.messageManager.searchWithChannel('全局某个channel消息','1',WKChannelType.group);`
// 分页搜索某个channel的指定消息类型
`WKIM.shared.messageManager
                            .searchMsgWithChannelAndContentTypes(
                                '1', WKChannelType.personal, 0, 100, [1, 2]);`
