### ISSUE TITLE
获取@状态 reminders一直为空

### ISSUE THREAD

**Issue by Mortal-HY** [WuKongIM/WuKongIMFlutterSDK#31]
我在聊天列表中调用如下方法获取@ 状态 
`  String getReminderText(UIConversation uiConversation) {
    String content = "";
    if (uiConversation.reminders == null) {
      uiConversation.msg.getReminderList().then((value) {
        uiConversation.reminders = value;
        setState(() {});
      });
      return content;
    }
    if (uiConversation.reminders!.isNotEmpty) {
      for (var i = 0; i < uiConversation.reminders!.length; i++) {
        if (uiConversation.reminders![i].type ==
                WKMentionType.wkReminderTypeMentionMe &&
            uiConversation.reminders![i].done == 0) {
          content = uiConversation.reminders![i].data;
          content = '[有人@你]';
          break;
        }
      }
    }
    return content;
  }`

但reminders一直为空  我看到demo中在点击 “提醒项” 按钮时手动调用了             WKIM.shared.reminderManager.saveOrUpdateReminders(list);
方法  我是否也应在某个接口处调用该方法来给reminders赋值？
另外  我添加了提醒项的监听方法   addOnNewReminderListener   但当我使用其他用户在群内@当前用户时  该监听方法也没有任何反应
![QQ_1725849828559](https://github.com/user-attachments/assets/49a4be42-d836-4fa9-865a-f7e7773f9638)

**Comment by No8blackball** [comment]
`WKIM.shared.reminderManager.saveOrUpdateReminders(list)` 需要你同步你们自己业务服务器的数据后报错后，才能获取到提醒项

**Comment by No8blackball** [comment]
`WKIM.shared.reminderManager.saveOrUpdateReminders(list)` 需要你同步你们自己业务服务器的数据后报错后，才能获取到提醒项

**Comment by Mortal-HY** [comment]
> `WKIM.shared.reminderManager.saveOrUpdateReminders(list)` 需要你同步你们自己业务服务器的数据后报错后，才能获取到提醒项

是在发送@消息后 发送方调用唐僧叨叨的接口同步@信息吗？同步返回成功后再调用WKIM.shared.reminderManager.saveOrUpdateReminders(list)方法吗？ 如果是的话是哪个接口呢  文档中并没有找到@消息相关的接口

**Comment by No8blackball** [comment]
> > `WKIM.shared.reminderManager.saveOrUpdateReminders(list)` 需要你同步你们自己业务服务器的数据后报错后，才能获取到提醒项
> 
> 是在发送@消息后 发送方调用唐僧叨叨的接口同步@信息吗？同步返回成功后再调用WKIM.shared.reminderManager.saveOrUpdateReminders(list)方法吗？ 如果是的话是哪个接口呢 文档中并没有找到@消息相关的接口

再收到@消息时，会收到同步提醒项的cmd。收到该cmd时就需要去同步提醒项，这里的接口是指你们自己业务服务器的接口。具体可以参考唐僧叨叨实现
