### ISSUE TITLE
Initialization vector must be the same length as block size

### ISSUE THREAD

**Issue by lch872** [WuKongIM/WuKongIMFlutterSDK#35]
flutter: error: Invalid argument(s): Initialization vector must be the same length as block size
flutter: 
flutter: #0      CBCBlockCipher.init (package:pointycastle/block/modes/cbc.dart:52:7)
flutter: #1      PaddedBlockCipherImpl.init (package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:47:12)
flutter: #2      AES.encrypt (package:encrypt/src/algorithms/aes.dart:40:9)
flutter: #3      Encrypter.encryptBytes (package:encrypt/src/encrypter.dart:12:19)
flutter: #4      Encrypter.encrypt (package:encrypt/src/encrypter.dart:28:12)
flutter: #5      CryptoUtils.aesEncrypt (package:wukongimfluttersdk/common/crypto_utils.dart:40:22)
flutter: #6      SendPacket.encodeMsgContent (package:wukongimfluttersdk/proto/packet.dart:91:24)
flutter: #7      SendPacket.encodeMsgKey (package:wukongimfluttersdk/proto/packet.dart:79:22)
flutter: #8      encodeSend (package:wukongimfluttersdk/proto/proto.dart:182:28)
flutter: #9      Proto.encode (package:wukongimfluttersdk/proto/proto.dart:57:35)
flutter: #10     WKConnectionManager._sendPacket (package:wukongimfluttersdk/manager/connect_manager.dart:359:42)
flutter: #11     WKConnectionManager.sendMessage (package:wukongimfluttersdk/manager/connect_manager.dart:430:5)
flutter: #12     WKMessageManager.sendWithOption (package:wukongimfluttersdk/manager/message_manager.dart:668:37)
flutter: <asynchronous suspension>

**Comment by No8blackball** [comment]
你们有改动sdk吗，我在我们example上未发现该问题

**Comment by lch872** [comment]
问题应该解决了，错误的调用2次了 init，估计是异步覆盖了 aesKey。
