### ISSUE TITLE
附件监听视频上传成功，回调也传了url  但是接收和发送的消息都没有url字段 只有localpath

### ISSUE THREAD

**Issue by unicornB** [WuKongIM/WuKongIMFlutterSDK#6]
封面都正常
视频缺少远程地址
`WKVideoContent videoContent = wkMsg.messageContent! as WKVideoContent;
        // todo 上传封面及视频
        //上传封面
        var attfile =
            await dio.MultipartFile.fromFile(videoContent.coverLocalPath);
        var formData = dio.FormData.fromMap({'file': attfile});
        final extension = p.extension(videoContent.coverLocalPath);
        final uid = await UserService.to.getUid();
        var uuid = const Uuid();
        var uuidStr = uuid.v1();
        String path = "${UploadPath.chatVideoCover}/$uid/$uuidStr$extension";
        var uploadRes = await Api.uploadFile(formData, UploadType.chat, path);
        String coverUrl = "${Config.baseUrl}/v1/${uploadRes['path']}";
        videoContent.cover = coverUrl;
        //压缩视频
        MediaInfo? mediaInfo = await VideoCompress.compressVideo(
          videoContent.localPath,
          quality: VideoQuality.Res640x480Quality,
          deleteOrigin: false, // It's false by default
        );
        //上传视频
        var videofile = await dio.MultipartFile.fromFile(mediaInfo!.path!);
        var videoFormData = dio.FormData.fromMap({'file': videofile});
        final videoExtension = p.extension(videoContent.localPath);
        String videoPath =
            "${UploadPath.chatVideo}/$uid/$uuidStr$videoExtension";
        var videoUploadRes =
            await Api.uploadFile(videoFormData, UploadType.chat, videoPath);
        String videoUrl = "${Config.baseUrl}/v1/${videoUploadRes['path']}";
        log("视频地址$videoUrl");
        videoContent.url = videoUrl;

        wkMsg.messageContent = videoContent;
        back(wkMsg);`

**Comment by No8blackball** [comment]
Upgrade to the latest

**Comment by unicornB** [comment]
已解决
