### ISSUE TITLE
oldestOrderSeq>0 时 WKIM.shared.messageManager.getOrSyncHistoryMessages message..type两个点

### ISSUE THREAD

**Issue by unicornB** [WuKongIM/WuKongIMFlutterSDK#7]
`Exception has occurred.
SqfliteDatabaseException (DatabaseException(near ".": syntax error (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT * FROM (SELECT message.client_seq,message.message_id,message.message_seq,message.channel_id,message.channel_type,message.timestamp,message.topic_id,message.from_uid,message.type,message.content,message.status,message.voice_status,message.created_at,message.updated_at,message.searchable_word,message.client_msg_no,message.setting,message.order_seq,message.extra,message.is_deleted,message.flame,message.flame_second,message.viewed,message.viewed_at,IFNULL(message_extra.readed,0) as readed,IFNULL(message_extra.readed_count,0) as readed_count,IFNULL(message_extra.unread_count,0) as unread_count,IFNULL(message_extra.revoke,0) as revoke,IFNULL(message_extra.revoker,'') as revoker,IFNULL(message_extra.extra_version,0) as extra_version,IFNULL(message_extra.is_mutual_deleted,0) as is_mutual_deleted,IFNULL(message_extra.need_upload,0) as need_upload,IFNULL(message_extra.content_edit,'') as content_edit,IFNULL(message_extra.edited_at,0) as edited_at FROM message LEFT JOIN message_extra on message.message_id=message_extra.message_id WHERE message.channel_id='4ee3677196724074aa2af45e9f529653' and message.channel_type=1 and message..type<>0 and message.type<>99 AND message.order_seq>=115000) where is_deleted=0 and is_mutual_deleted=0 order by order_seq asc limit 0,20, (OS error - 2:No such file or directory)) sql 'SELECT * FROM (SELECT message.client_seq,message.message_id,message.message_seq,message.channel_id,message.channel_type,message.timestamp,message.topic_id,message.from_uid,message.type,message.content,message.status,message.voice_status,message.created_at,message.updated_at,message.searchable_word,message.client_msg_no,message.setting,message.order_seq,message.extra,message.is_deleted,message.flame,message.flame_second,message.viewed,message.viewed_at,IFNULL(message_extra.readed,0) as readed,IFNULL(message_extra.readed_count,0) as readed_count,IFNULL(message_extra.unread_count,0) as unread_count,IFNULL(message_extra.revoke,0) as revoke,IFNULL(message_extra.revoker,'') as revoker,IFNULL(message_extra.extra_version,0) as extra_version,IFNULL(message_extra.is_mutual_deleted,0) as is_mutual_deleted,IFNULL(message_extra.need_upload,0) as need_upload,IFNULL(message_extra.content_edit,'') as content_edit,IFNULL(message_extra.edited_at,0) as edited_at FROM message LEFT JOIN message_extra on message.message_id=message_extra.message_id WHERE message.channel_id='4ee3677196724074aa2af45e9f529653' and message.channel_type=1 and message..type<>0 and message.type<>99 AND message.order_seq>=115000) where is_deleted=0 and is_mutual_deleted=0 order by order_seq asc limit 0,20' args [])`

**Comment by No8blackball** [comment]
更新sdk到1.0.9
